"""user_games table

Revision ID: 83c5aa9c4e1b
Revises: ae1213309502
Create Date: 2024-02-14 14:34:20.720187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c5aa9c4e1b'
down_revision = 'ae1213309502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=10), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_games_created_at'), [
                              'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_games_game_id'), [
                              'game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_games_user_id'), [
                              'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_games_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_games_game_id'))
        batch_op.drop_index(batch_op.f('ix_user_games_created_at'))

    op.drop_table('user_games')
    # ### end Alembic commands ###
